POST http://desktop-dgjb2o5:56996/users
Content-Type: application/json

{
  "email" : "hackerljm@gmail.com",
  "name" : "Jeongmuk Lim",
  "pwd" : "test1234"
}

###
POST http://desktop-dgjb2o5:56996/users
Content-Type: application/json

{
"email" : "hackerljm@naver.com",
"name" : "Jeongmuk Lim naver",
"pwd" : "test1234"
}

###
GET http://127.0.0.1:8000/user-service/users
Content-Type: application/json


###
GET http://127.0.0.1:8000/user-service/users/52f27522-c53c-4f2f-93b1-9cc519d9f2d2
Content-Type: application/json


###
POST http://127.0.0.1:8000/user-service/users
Content-Type: application/json

{
"email" : "hackerljm@gmail.com",
"name" : "Jeongmuk Lim",
"pwd" : "test1234"
}

###
POST http://127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email" : "hackerljm@naver.com",
  "name" : "Jeongmuk Lim naver",
  "pwd" : "test1234"
}

