POST http://127.0.0.1:8000/user-service/users
Content-Type: application/json

{
  "email" : "hackerljm@gmail.com",
  "name" : "Jeongmuk Lim",
  "pwd" : "test1234"
}

###
POST http://127.0.0.1:8000/user-service/users
Content-Type: application/json

{
"email" : "hackerljm@naver.com",
"name" : "Jeongmuk Lim naver",
"pwd" : "test1234"
}

###
GET http://127.0.0.1:8000/user-service/users
Content-Type: application/json


###
GET http://127.0.0.1:8000/user-service/users/7d53e1f1-70d4-4d63-b7c9-575cfb568409
Content-Type: application/json


###
POST http://127.0.0.1:8000/user-service/login
Content-Type: application/json

{
"email" : "hackerljm@gmail.com",
"password" : "test1234"
}


###
POST http://127.0.0.1:8000/user-service/login
Content-Type: application/json

{
  "email" : "hackerljm@naver.com",
  "password" : "test1234"
}